// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMMIzFb51ujalvcbHlpsQhZ2O9LuHaKaU',
    appId: '1:589601474347:android:c058b2f227996eb366a76e',
    messagingSenderId: '589601474347',
    projectId: 'the-bits-project',
    storageBucket: 'the-bits-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQlRZjpqQQwB9Tv9fbpGGzF1uQd4fzzlE',
    appId: '1:589601474347:ios:6c29a8b2eb13519a66a76e',
    messagingSenderId: '589601474347',
    projectId: 'the-bits-project',
    storageBucket: 'the-bits-project.appspot.com',
    iosClientId: '589601474347-vdb82jff7a2jebnmtlaa7o1eloaj0d3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitsapp',
  );
}
